#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$LF_FIFO_UEBERZUG"
	{
	"action": "add", "identifier": "lf-preview",
    "path": "$1", "x": $(($4 +1)), "y": $5, "width": $(($2 - 3)), "height": $3,
	"scaler": "contain"
	}
	EOF
}

lf-cleaner # clean active preview

file="$1"; shift
case "$file" in
    *.tar.gz) tar -ztvf "$file";;
    *.tar.bz2) tar -jtvf "$file";;
    *.tar) tar -tvf "$file";;
    *.zip) zipinfo "$file";;
    *.rar) unrar l "$file";;
    *.md) glow -s dark "$file";;
    *.7z) 7z l "$file" ;;
    *.html|*.xml) w3m -dump "$file";;
    *.avi|*.mp4|*.mkv|*.webm|*.m4a)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.pdf)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        gs -o "$thumbnail" -sDEVICE=pngalpha -dMAxBitmap=500000000 -dAlignToPixles=0 -dGridFitTT=0 -r150x150 -dLastPage=1 "$file" >/dev/null
        preview "$thumbnail" "$@"
        ;;
    *.ogg)
        mediainfo "$file" ;;
    *.png|*.jpg|*.jpeg)
        preview "$file" "$@" ;;
    *.svg)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        convert "$file" "$thumbnail"
        preview "$thumbnail" "$@"
        ;;
    *.epub)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        epub-thumbnailer "$file" "$thumbnail" 1080
        preview "$thumbnail" "$@"
        ;;
    *) highlight "$file" -O ansi --force ;;
esac
return 127 # nonzero retcode required for lf previews to reload
