#!/bin/sh

mopidy &
setbg &
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
picom &		# picom for transparency
dunst &			# dunst for notifications
unclutter &		# Remove mouse when idle
dwmblocks &   # Bar for dwm
exec kmonad ~/.config/kmonad/config.kbd &   #keyboard remapping
# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

