# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[](bold green) "
error_symbol = "[](bold red) "
vicmd_symbol = "[](bold green)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true

[cmd_duration]
min_time = 10000
format = "underwent [$duration](bold yellow)"

[directory]
truncation_length = 8
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"

[aws]
disabled = true

[battery]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true


[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nix_shell]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
